### PR TITLE
Fix preselected values causing undefined errors

### PR DESCRIPTION
**Pull request by jonheslop**
Prefilled result is passed to the template as a string not an object

So we need to add a check to see if is an object else use the string

Which fixes https://github.com/alphagov/accessible-autocomplete/issues/383

### CODE REVIEW

**Comment by nickcolley** [comment]
I think this is indeed the right place to be thinking of a fix, since the 'undefined' value was always in the list but the thing that has changed upstream is when the menu opens.

**Comment by nickcolley** [comment]
I think if we remove the test example here and add a CHANGELOG entry we'll be able to ship this next week.

Ideally we'd have a test but not sure that's easy on this repository.

**Comment by nickcolley** [comment]
Hmm testing this there's some really weird behaviour where the menu will never close after first focusing it with a mouse.

Wondering if we should slow down and try to clarify the menu behaviour upstream, or if this is still a good fix to roll out...

**Comment by nickcolley** [comment]
Actually it's still erroring on 'blur'.

Tip for anyone else who wants a good JavaScript error stack trace

1. run `npm run build`
2. run `npx http-server`
3. go to `http://127.0.0.1:8080/examples/`

For some reason the dev build stack traces swallow the original location so it's hard to know what has broken.

**Comment by nickcolley** [comment]
I've figured it out, the inputValue template needs to handle this change in data structure too.

I wonder if there's a sensible way to fallback if these templates fail upstream, maybe to fallback to not templating?

**Comment by nickcolley** [comment]
I think for now we'll go with the downstream fixes, but if this comes up again for other users downstream, we can do something like this upstream:

```js
templateSuggestion (value) {
    const suggestionTemplate = this.props.templates && this.props.templates.suggestion
    var templatedSuggestion
    // Check that the template is a function that we can use
    if (typeof suggestionTemplate === 'function') {
      templatedSuggestion = suggestionTemplate(value)
    }
    // Check that the templated value is not undefined
    return typeof templatedSuggestion !== 'undefined' ? templatedSuggestion : value
  }
```

**Comment by jonheslop** [comment]
Nice one Nick, just tried it out and its working 🙌

**Pull request merged**
