### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by colinrotherham**
Due to some IE11 issues I've recently opened:
https://github.com/alphagov/accessible-autocomplete/pull/310
https://github.com/alphagov/accessible-autocomplete/pull/316

Thanks to `@babel/preset-env` we can now add automatic polyfills using `browserslist` 👍 

But, due to the webpack + babel build in this project it will undo some of these new tweaks.

So… I've applied the same fixes here as well 😊

### CODE REVIEW

**Comment by colinrotherham** [comment]
We'll still need to do a version bump for https://github.com/alphagov/accessible-autocomplete and roll it into this pull request

**Comment by injms** [comment]
Super - this looks good and works as expect in IE8 - 11, plus the other [required browsers](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices).

We just need to wait for this pull request (https://github.com/alphagov/accessible-autocomplete/pull/316) to be published before we can bump the `accessible-autocomplete` dependency here. ⏳

**Comment by colinrotherham** [comment]
@injms Progress, https://github.com/alphagov/accessible-autocomplete/pull/316 has been merged now just waiting for a new npm release.

**Comment by colinrotherham** [comment]
Added updates from the last week including `accessible-autocomplete@1.6.2`

This is now ready @injms

**Comment by injms** [comment]
Superduper! Thanks for doing this @colinrotherham - very much appreciated 🥇

**Comment by colinrotherham** [comment]
Brill thanks @injms.

Can you please version, tag and publish to npm please? Thanks

**Pull request merged**
